insert into estados values(null,'Aguascalientes');
insert into estados values(null,'Baja California');
insert into estados values(null,'Baja California Sur');
insert into estados values(null,'Campeche');
insert into estados values(null,'Chiapas');
insert into estados values(null,'Chihuahua');
insert into estados values(null,'Ciudad de México');
insert into estados values(null,'Coahuila');
insert into estados values(null,'Colima');
insert into estados values(null,'Durango');
insert into estados values(null,'Guanajuato');
insert into estados values(null,'Guerrero');
insert into estados values(null,'Hidalgo');
insert into estados values(null,'Jalisco');
insert into estados values(null,'México');
insert into estados values(null,'Michoacán');
insert into estados values(null,'Morelos');
insert into estados values(null,'Nayarit');
insert into estados values(null,'Nuevo León');
insert into estados values(null,'Oaxaca');
insert into estados values(null,'Puebla');
insert into estados values(null,'Querétaro');
insert into estados values(null,'Quintana Roo');
insert into estados values(null,'San Luis Potosí');
insert into estados values(null,'Sinaloa');
insert into estados values(null,'Sonora');
insert into estados values(null,'Tabasco');
insert into estados values(null,'Tamaulipas');
insert into estados values(null,'Tlaxcala');
insert into estados values(null,'Veracruz');
insert into estados values(null,'Yucatán');
insert into estados values(null,'Zacatecas');