insert into municipios values(null,"Acajete",30,10);
insert into municipios values(null,"Acatlán",30,5);
insert into municipios values(null,"Acayucan",30,2);
insert into municipios values(null,"Actopan",30,2);
insert into municipios values(null,"Acula",30,2);
insert into municipios values(null,"Acultzingo",30,5);
insert into municipios values(null,"Camarón de Tejeda",30,2);
insert into municipios values(null,"Alpatláhuac",30,5);
insert into municipios values(null,"Alto Lucero de Gutiérrez Barrios",30,2);
insert into municipios values(null,"Altotonga",30,5);
insert into municipios values(null,"Alvarado",30,2);
insert into municipios values(null,"Amatitlán",30,2);
insert into municipios values(null,"Naranjos Amatlán",30,2);
insert into municipios values(null,"Amatlán de los Reyes",30,5);
insert into municipios values(null,"Ángel R. Cabada",30,2);
insert into municipios values(null,"La Antigua",30,2);
insert into municipios values(null,"Apazapan",30,2);
insert into municipios values(null,"Aquila",30,5);
insert into municipios values(null,"Astacinga",30,10);
insert into municipios values(null,"Atlahuilco",30,10);
insert into municipios values(null,"Atoyac",30,5);
insert into municipios values(null,"Atzacan",30,10);
insert into municipios values(null,"Atzalan",30,5);
insert into municipios values(null,"Tlaltetela",30,5);
insert into municipios values(null,"Ayahualulco",30,10);
insert into municipios values(null,"Banderilla",30,5);
insert into municipios values(null,"Benito Juárez",30,5);
insert into municipios values(null,"Boca del Río",30,2);
insert into municipios values(null,"Calcahualco",30,5);
insert into municipios values(null,"Camerino Z. Mendoza",30,5);
insert into municipios values(null,"Carrillo Puerto",30,2);
insert into municipios values(null,"Catemaco",30,5);
insert into municipios values(null,"Cazones de Herrera",30,2);
insert into municipios values(null,"Cerro Azul",30,2);
insert into municipios values(null,"Citlaltépetl",30,2);
insert into municipios values(null,"Coacoatzintla",30,5);
insert into municipios values(null,"Coahuitlán",30,2);
insert into municipios values(null,"Coatepec",30,5);
insert into municipios values(null,"Coatzacoalcos",30,2);
insert into municipios values(null,"Coatzintla",30,2);
insert into municipios values(null,"Coetzala",30,10);
insert into municipios values(null,"Colipa",30,2);
insert into municipios values(null,"Comapa",30,2);
insert into municipios values(null,"Córdoba",30,2);
insert into municipios values(null,"Cosamaloapan de Carpio",30,2);
insert into municipios values(null,"Cosautlán de Carvajal",30,10);
insert into municipios values(null,"Coscomatepec",30,10);
insert into municipios values(null,"Cosoleacaque",30,5);
insert into municipios values(null,"Cotaxtla",30,2);
insert into municipios values(null,"Coxquihui",30,10);
insert into municipios values(null,"Coyutla",30,2);
insert into municipios values(null,"Cuichapa",30,10);
insert into municipios values(null,"Cuitláhuac",30,2);
insert into municipios values(null,"Chacaltianguis",30,2);
insert into municipios values(null,"Chalma",30,2);
insert into municipios values(null,"Chiconamel",30,2);
insert into municipios values(null,"Chiconquiaco",30,5);
insert into municipios values(null,"Chicontepec",30,2);
insert into municipios values(null,"Chinameca",30,2);
insert into municipios values(null,"Chinampa de Gorostiza",30,2);
insert into municipios values(null,"Las Choapas",30,2);
insert into municipios values(null,"Chocamán",30,10);
insert into municipios values(null,"Chontla",30,2);
insert into municipios values(null,"Chumatlán",30,2);
insert into municipios values(null,"Emiliano Zapata",30,5);
insert into municipios values(null,"Espinal",30,2);
insert into municipios values(null,"Filomeno Mata",30,2);
insert into municipios values(null,"Fortín",30,2);
insert into municipios values(null,"Gutiérrez Zamora",30,2);
insert into municipios values(null,"Hidalgotitlán",30,2);
insert into municipios values(null,"Huatusco",30,5);
insert into municipios values(null,"Huayacocotla",30,10);
insert into municipios values(null,"Hueyapan de Ocampo",30,2);
insert into municipios values(null,"Huiloapan de Cuauhtémoc",30,5);
insert into municipios values(null,"Ignacio de la Llave",30,2);
insert into municipios values(null,"Ilamatlán",30,5);
insert into municipios values(null,"Isla",30,2);
insert into municipios values(null,"Ixcatepec",30,5);
insert into municipios values(null,"Ixhuacán de los Reyes",30,10);
insert into municipios values(null,"Ixhuatlán del Café",30,10);
insert into municipios values(null,"Ixhuatlancillo",30,5);
insert into municipios values(null,"Ixhuatlán del Sureste",30,2);
insert into municipios values(null,"Ixhuatlán de Madero",30,2);
insert into municipios values(null,"Ixmatlahuacan",30,2);
insert into municipios values(null,"Ixtaczoquitlán",30,5);
insert into municipios values(null,"Jalacingo",30,2);
insert into municipios values(null,"Xalapa",30,5);
insert into municipios values(null,"Jalcomulco",30,2);
insert into municipios values(null,"Jáltipan de Morelos",30,2);
insert into municipios values(null,"Jamapa",30,2);
insert into municipios values(null,"Jesús Carranza",30,2);
insert into municipios values(null,"Xico",30,5);
insert into municipios values(null,"Jilotepec",30,10);
insert into municipios values(null,"Juan Rodríguez Clara",30,2);
insert into municipios values(null,"Juchique de Ferrer",30,2);
insert into municipios values(null,"Landero y Coss",30,5);
insert into municipios values(null,"Lerdo de Tejada",30,2);
insert into municipios values(null,"Magdalena",30,10);
insert into municipios values(null,"Maltrata",30,10);
insert into municipios values(null,"Manlio Fabio Altamirano",30,2);
insert into municipios values(null,"Mariano Escobedo",30,5);
insert into municipios values(null,"Martínez de la Torre",30,2);
insert into municipios values(null,"Mecatlán",30,5);
insert into municipios values(null,"Mecayapan",30,2);
insert into municipios values(null,"Medellín",30,5);
insert into municipios values(null,"Miahuatlán",30,5);
insert into municipios values(null,"Las Minas",30,5);
insert into municipios values(null,"Minatitlán",30,5);
insert into municipios values(null,"Misantla",30,5);
insert into municipios values(null,"Mixtla de Altamirano",30,3);
insert into municipios values(null,"Moloacán",30,2);
insert into municipios values(null,"Naolinco",30,5);
insert into municipios values(null,"Naranjal",30,5);
insert into municipios values(null,"Nautla",30,5);
insert into municipios values(null,"Nogales",30,10);
insert into municipios values(null,"Oluta",30,2);
insert into municipios values(null,"Omealca",30,5);
insert into municipios values(null,"Orizaba",30,10);
insert into municipios values(null,"Otatitlán",30,5);
insert into municipios values(null,"Oteapan",30,2);
insert into municipios values(null,"Ozuluama de Mascareñas",30,2);
insert into municipios values(null,"Pajapan",30,2);
insert into municipios values(null,"Pánuco",30,5);
insert into municipios values(null,"Papantla",30,2);
insert into municipios values(null,"Paso del Macho",30,3);
insert into municipios values(null,"Paso de Ovejas",30,3);
insert into municipios values(null,"La Perla",30,10);
insert into municipios values(null,"Perote",30,10);
insert into municipios values(null,"Platón Sánchez",30,2);
insert into municipios values(null,"Playa Vicente",30,5);
insert into municipios values(null,"Poza Rica de Hidalgo",30,2);
insert into municipios values(null,"Las Vigas de Ramírez",30,5);
insert into municipios values(null,"Pueblo Viejo",30,2);
insert into municipios values(null,"Puente Nacional",30,2);
insert into municipios values(null,"Rafael Delgado",30,5);
insert into municipios values(null,"Rafael Lucio",30,5);
insert into municipios values(null,"Los Reyes",30,10);
insert into municipios values(null,"Río Blanco",30,5);
insert into municipios values(null,"Saltabarranca",30,2);
insert into municipios values(null,"San Andrés Tenejapan",30,5);
insert into municipios values(null,"San Andrés Tuxtla",30,5);
insert into municipios values(null,"San Juan Evangelista ",30,2);
insert into municipios values(null,"Santiago Tuxtla",30,5);
insert into municipios values(null,"Sayula de Alemán",30,5);
insert into municipios values(null,"Soconusco",30,2);
insert into municipios values(null,"Sochiapa",30,5);
insert into municipios values(null,"Soledad Atzompa",30,10);
insert into municipios values(null,"Soledad de Doblado",30,3);
insert into municipios values(null,"Soteapan",30,2);
insert into municipios values(null,"Tamalín",30,2);
insert into municipios values(null,"Tamiahua",30,3);
insert into municipios values(null,"Tampico Alto",30,3);
insert into municipios values(null,"Tancoco",30,2);
insert into municipios values(null,"Tantima",30,3);
insert into municipios values(null,"Tantoyuca",30,3);
insert into municipios values(null,"Tatatila",30,5);
insert into municipios values(null,"Castillo de Teayo",30,5);
insert into municipios values(null,"Tecolutla",30,2);
insert into municipios values(null,"Tehuipango",30,10);
insert into municipios values(null,"Álamo Temapache",30,5);
insert into municipios values(null,"Tempoal",30,3);
insert into municipios values(null,"Tenampa",30,5);
insert into municipios values(null,"Tenochtitlán",30,5);
insert into municipios values(null,"Teocelo",30,5);
insert into municipios values(null,"Tepatlaxco",30,10);
insert into municipios values(null,"Tepetlán",30,10);
insert into municipios values(null,"Tepetzintla",30,3);
insert into municipios values(null,"Tequila",30,5);
insert into municipios values(null,"José Azueta",30,2);
insert into municipios values(null,"Texcatepec",30,5);
insert into municipios values(null,"Texhuacán",30,5);
insert into municipios values(null,"Texistepec",30,5);
insert into municipios values(null,"Tezonapa",30,5);
insert into municipios values(null,"Tierra Blanca",30,3);
insert into municipios values(null,"Tihuatlán",30,2);
insert into municipios values(null,"Tlacojalpan",30,2);
insert into municipios values(null,"Tlacolulan",30,5);
insert into municipios values(null,"Tlacotalpan",30,2);
insert into municipios values(null,"Tlacotepec de Mejía",30,10);
insert into municipios values(null,"Tlachichilco",30,5);
insert into municipios values(null,"Tlalixcoyan",30,2);
insert into municipios values(null,"Tlalnelhuayocan",30,5);
insert into municipios values(null,"Tlapacoyan",30,2);
insert into municipios values(null,"Tlaquilpa",30,10);
insert into municipios values(null,"Tlilapan",30,5);
insert into municipios values(null,"Tomatlán",30,5);
insert into municipios values(null,"Tonayán",30,5);
insert into municipios values(null,"Totutla",30,5);
insert into municipios values(null,"Tuxpan",30,2);
insert into municipios values(null,"Tuxtilla",30,5);
insert into municipios values(null,"Úrsulo Galván",30,2);
insert into municipios values(null,"Vega de Alatorre",30,5);
insert into municipios values(null,"Veracruz",30,2);
insert into municipios values(null,"Villa Aldama",30,5);
insert into municipios values(null,"Xoxocotla",30,5);
insert into municipios values(null,"Yanga",30,5);
insert into municipios values(null,"Yecuatla",30,2);
insert into municipios values(null,"Zacualpan",30,5);
insert into municipios values(null,"Zaragoza",30,2);
insert into municipios values(null,"Zentla",30,2);
insert into municipios values(null,"Zongolica",30,5);
insert into municipios values(null,"Zontecomatlán de López y Fuentes",30,5);
insert into municipios values(null,"Zozocolco de Hidalgo",30,5);
insert into municipios values(null,"Agua Dulce",30,2);
insert into municipios values(null,"El Higo",30,2);
insert into municipios values(null,"Nanchital de Lázaro Cárdenas del Río",30,2);
insert into municipios values(null,"Tres Valles",30,5);
insert into municipios values(null,"Carlos A. Carrillo",30,5);
insert into municipios values(null,"Tatahuicapan de Juárez",30,2);
insert into municipios values(null,"Uxpanapa",30,5);
insert into municipios values(null,"San Rafael",30,2);
insert into municipios values(null,"Santiago Sochiapan",30,2);