use kidneys;

#FRUTRAS
INSERT INTO foods VALUES (null, 'Manzana', 'La manzana es una fruta pomácea comestible, fruta del manzano comestible (Malus domestica), otros manzanos (especies del género Malus) o híbridos de aquel.', 1, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Manzana.jpg', 1, '100 grs', '107 mg', '120 mg', '11 mg');
INSERT INTO foods VALUES (null, 'Pera', 'fruto de distintas especies del género Pyrus, integrado por árboles caducifolios conocidos comúnmente como perales.', 1, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Pera.jpg', 1, '100 grs', '1 mg', '101 mg', '11 mg');
INSERT INTO foods VALUES (null, 'Durazno', 'El  aterciopelado  durazno  se  cultivó  originalmente  en  China,  donde  era  considerado  fuente  de  una larga  vida  y su imagen se  usó para decorar la más fina porcelana. En México se cultiva a gran escala  y en los  patios  de  muchas  casas.', 1, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Durazno.jpg', 2, '100 grs', '0 gr', '190 mg', '65 mg');
INSERT INTO foods VALUES (null, 'Aguacate', 'Antes que los humanos gozáramos de los aguacates, fueron un fruto preferido de los grandes mamíferos de la Edad de Hielo.', 1, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Aguacate.jpg', 3, '100 grs', '7 mg', '485 mg', '52 mg');
INSERT INTO foods VALUES (null, 'Arandanos', 'Arbusto de tallo reptante, ramas erectas, hojas alternas y ovaladas, con pecíolo corto, de color verde claro, flores blancas o rosadas y fruto en forma de baya esférica; puede alcanzar hasta 60 cm de altura.', 1, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Arandanos.jpg', 1, '100 grs', '1 mg', '77 mg', '12 mg');
INSERT INTO foods VALUES (null, 'Mango', 'Es el nombre de las frutas de varias especies de árboles del género Mangifera, especialmente Mangifera indica y sus numerosos cultivares.', 1, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Mango.jpg', 3, '100 grs', '1 mg', '168 mg', '14 mg');
INSERT INTO foods VALUES (null, 'Platano', 'Fruto del platanero, comestible, de forma alargada y algo curvada, pulpa de color blanco y piel lisa de color amarillo que se desprende con facilidad.', 1, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Platano.jpg', 3, '100 grs', '4 mg', '499 mg', '34 mg');
INSERT INTO foods VALUES (null, 'Uva', 'Fruto de la vid, comestible, pequeño y de forma redonda u ovalada, piel muy fina y carne muy jugosa; nace junto a otros formando racimos.', 1, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Uva.jpg', 2, '100 grs', '1 mg', '203 mg', '24 mg');
INSERT INTO foods VALUES (null, 'Piña', 'Planta tropical de hojas espinosas, largas y hendidas, flores de color morado y fruto carnoso y comestible.', 1, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Piña.jpg', 2, '100 grs', '1 mg', '109 mg', '8 mg');
INSERT INTO foods VALUES (null, 'Cereza', 'Fruto del cerezo, pequeño y redondeado, de color rojo oscuro, pulpa dulce y jugosa y un hueso en su interior.', 1, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Cereza.jpg', 2, '100 grs', '13 mg', '376 mg', '36 mg');

#VERDURAS
INSERT INTO foods VALUES (null, 'Brocoli', 'Este es un tipo de plantas perteneciente a la familia de las Brasicaceas, familia de la cual es miembro el coliflor, estos son comestibles, muy parecido al coliflor solo que esta planta es de color verde oscuro.', 2, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Brocoli.jpg', 3, '100 grs', '33 mg', '316 mg', '66 mg');
INSERT INTO foods VALUES (null, 'Cebolla', 'Planta hortícola de tallo hueco, fusiforme e hinchado hacia la base, hojas largas y estrechas, flores blancas o rosadas, agrupadas en umbelas, fruto en cápsulas muy pequeñas, lleno de semillas diminutas, y bulbo comestible.', 2, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Cebolla.jpg', 1, '100 grs', '4 mg', '146 mg', '29 mg');
INSERT INTO foods VALUES (null, 'Champiñon', 'Hongo comestible de sombrero globoso o acampanado y pie cilíndrico de color claro, con un anillo en la parte superior.', 2, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Champiñon.jpg', 3, '100 grs', '11 mg', '437 mg', '135 mg');
INSERT INTO foods VALUES (null, 'Lechuga', 'Planta hortícola de hojas grandes, verdes, enteras o dentadas, las inferiores agrupadas en roseta, de cuyo centro nace un tallo cilíndrico ramificado que lleva en el ápice numerosos capítulos amarillos y fruto seco, gris con una única semilla.', 2, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Lechuga.jpg', 1, '100 grs', '5 mg', '238 mg', '33 mg');
INSERT INTO foods VALUES (null, 'Pepino', 'Fruto de esta planta, comestible, de forma cilíndrica, corteza áspera y rugosa, verde o amarilla, y en su interior una carne blanca con muchas semillas pequeñas y planas en el centro.', 2, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Pepino.jpg', 1, '100 grs', '2 mg', '147 mg', '24 mg');
INSERT INTO foods VALUES (null, 'Pimiento Verde', 'El pimiento es el fruto hueco de una planta herbácea que recibe su mismo nombre, el pimiento verde es aquel que todavía no han madurado.', 2, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/PimientoVerde.jpg', 1, '100 grs', '1 mg', '187 mg', '17 mg');
INSERT INTO foods VALUES (null, 'Tomate', 'Es el fruto de la planta conocida como tomatera, una especie herbácea que pertenece a la familia de las solanáceas y es nativa del continente americano. Los tomates son bayas de color rojizo que se caracterizan por su pulpa con múltiples semillas.', 2, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Tomate.jpg', 3, '100 grs', '13 mg', '204 mg', '28 mg');
INSERT INTO foods VALUES (null, 'Zanahoria', 'Es una planta herbácea hojas recortadas, flores blancas y raíz puntiaguda, jugosa y comestible, Es la hortaliza más importante y de mayor y consumo de la familia.', 2, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Zanahoria.jpg', 1, '100 grs', '69 mg', '320 mg', '35 mg');
INSERT INTO foods VALUES (null, 'Ajo', 'Gajo o parte en que está dividido el bulbo de esta planta, de pulpa blanquecina o amarillenta y sabor muy fuerte, picante y característico.', 2, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Ajo.jpg', 1, '100 grs', '17 mg', '401 mg', '153 mg');
INSERT INTO foods VALUES (null, 'Calabacin', 'Variedad de calabaza, de pequeño tamaño, forma cilíndrica, parecida a la del pepino, y carne blanca cubierta por una corteza verde.', 2, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Calabacin.jpg', 3, '100 grs', '2 mg', '150 mg', '13 mg');
INSERT INTO foods VALUES (null, 'Espinaca', 'Planta hortícola de tallo ramoso, hojas estrechas y suaves, unidas por la base y de tallo rojizo, flores sin corola y semillas redondas o con pequeños cuernos.', 2, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Espinaca.jpg', 3, '100 grs', '79 mg', '558 mg', '49 mg');

#CEREALES, TUBERCULOS Y LEGUMBRES
INSERT INTO foods VALUES (null, 'Arroz', 'Fruto de esta planta, comestible, en forma de grano alargado, de color blanquecino, y dispuesto en una panícula formada por varias espiguillas que crece en el ápice del tallo.', 3, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Arroz.jpg', 2, '100 grs', '5 mg', '115 mg', '115 mg');
INSERT INTO foods VALUES (null, 'Frijoles', 'Los frijoles son un  alimento muy nutritivo y un elemento fundamental en la mesa de los mexicanos.', 3, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Frijoles.jpg', 3, '100', '252 mg', '285 mg', '71 mg');
INSERT INTO foods VALUES (null, 'Avena', 'Es una planta herbácea anual, perteneciente a la familia de las poaceae. Las especies más cultivadas son Avena sativa y Avena byzantina, en ese orden. Es rica en proteínas de alto valor biológico, grasas y un gran número de vitaminas y minerales.', 3, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Avena.jpg', 3, '100 grs', '2 mg', '429 mg', '523 mg');
INSERT INTO foods VALUES (null, 'Garbanzos', 'Semilla de esta planta, comestible, de pequeño tamaño, forma redondeada, con un ápice encorvado y color amarillento.', 3, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Garbanzos.jpg', 3, '100 grs', '24 mg', '718 mg', '252 mg');
INSERT INTO foods VALUES (null, 'Pan', 'Alimento básico que se elabora con una mezcla de harina, generalmente de trigo, agua, sal y levadura, que se amasa y se cuece en un horno en piezas de distintas formas y tamaños; su sabor, color y textura pueden variar según el tipo de harina empleado.', 3, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Pan.jpg', 2, '100 grs', '490 mg', '126 mg', '98 mg');
INSERT INTO foods VALUES (null, 'Pasta', 'conjunto de alimentos preparados con una masa cuyo ingrediente básico es la harina, mezclada con agua, y a la cual se puede añadir sal, huevo u otros ingredientes, conformando un producto que generalmente se cuece en agua hirviendo.', 3, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Pasta.jpg', 2, '100 grs', '3 mg', '294 mg', '253 mg');
INSERT INTO foods VALUES (null, 'Papa', 'Es un tubérculo que tiene su origen en Sudamérica pero que, en la actualidad, se cultiva en diversas regiones del planeta.', 3, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Papa.jpg', 2, '100 grs', '2 mg', '1 mg', '385 mg');
INSERT INTO foods VALUES (null, 'Guisante', 'Semilla de esta planta, comestible, de pequeño tamaño, forma redondeada y color verde.', 3, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Guisante.jpg', 3, '100 grs', '15 mg', '823 mg', '321 mg');
INSERT INTO foods VALUES (null, 'Habas', 'Planta herbácea de tallo erguido, ramoso y algo estriado, hojas compuestas de hojuelas elípticas, de color verde azulado, flores blancas o rosadas con manchas negras y fruto en legumbre.', 3, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Haba.jpg', 3, '100 grs', '13 mg', '307 mg', '100 mg');

#LACTEOS
INSERT INTO foods VALUES (null, 'Leche Deslactosada', 'Es una leche a la que se le ha retirado más del 90% de grasa, y que además puede ser mejor digerida.', 4, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/LecheDeslactosada.jpg', 2, '100 grs', '47 mg', '140 mg', '92 mg');
INSERT INTO foods VALUES (null, 'Queso Fresco', 'Queso sin madurar o escasamente madurado que se obtiene por coagulación de la leche por medio del cuajo o por fermentación láctica, que es de color blanco, sabor lechoso y consistencia cremosa.', 4, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/QuesoFresco.jpg', 2, '100 grs', '20 mg', '199 mg', '222 mg');
INSERT INTO foods VALUES (null, 'Queso Gouda', 'Es un queso amarillento neerlandés denominado así por la ciudad de Gouda. El término "gouda" es hoy en día un nombre genérico, no estando limitado a los quesos de origen neerlandés.', 4, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/QuesoGouda.jpg', 3, '100 grs', '2 mg', '200 mg', '800 mg');
INSERT INTO foods VALUES (null, 'Queso Parmesano', 'Es un famoso queso italiano de consistencia dura y granular. El parmesano se usa rallado o gratinado. Su producción se encuentra regulada por una DOP.', 4, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/QuesoParmesano.jpg', 1, '100 grs', '2 mg', '180 mg', '627 mg');
INSERT INTO foods VALUES (null, 'Yogurth', 'Alimento líquido y espeso o pastoso, de sabor agrio, que se obtiene por fermentación de la leche de vaca entera o desnatada.', 4, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Yogurth.jpg', 3, '100 grs', '66 mg', '219 mg', '135 mg');

#CARNES Y OTROS PROTEICOS
INSERT INTO foods VALUES (null, 'Tocino', 'Es un producto cárnico que comprende la piel y las capas que se encuentran bajo la piel del cerdo.', 5, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Tocino.jpg', 3, '100 grs', '2 mg', '145 mg', '217 mg');
INSERT INTO foods VALUES (null, 'Carne Bovina', 'Carne procedente de un animal no menor a 3 años de edad y que pese 500 kg. antes de su sacrificio, la carne es de color rojo en diferentes tonalidades, su contenido graso medio o alto según la raza y alimentación de la res.', 5, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/CarneBovina.jpg', 2, '100 grs', '56 mg', '305 mg', '168 mg');
INSERT INTO foods VALUES (null, 'Carne De Cerdo', 'Carne de puerco, carne de marrano, carne de cochino, carne de porcino o carne de chancho es un producto cárnico procedente del cerdo.', 5, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/CarneDeCerdo.jpg', 3, '100 grs', '125 mg', '36 mg', '160 mg');
INSERT INTO foods VALUES (null, 'Chorizo', 'Embutido de carne de cerdo o de vaca, de unos 3 cm de diámetro y 15 cm de largo y similar a la salchicha, que se come generalmente asado y servido al plato o como relleno de un sándwich.', 5, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Chorizo.jpg', 2, '100 grs', '1 mg', '398 mg', '150 mg');
INSERT INTO foods VALUES (null, 'Huevo', 'Huevo que ponen las aves, especialmente la gallina, y que se toma como alimento.', 5, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Huevo.jpg', 2, '100 grs', '146 mg', '222 mg', '220 mg');
INSERT INTO foods VALUES (null, 'Jamon', 'Pata trasera de cerdo, cruda o curada, que se destina al consumo alimenticio; también puede ser de otros animales.', 5, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Jamon.jpg', 2, '100 grs', '1 mg', '490 mg', '261 mg');
INSERT INTO foods VALUES (null, 'Pollo', 'Es como se denomina a los tejidos musculares y órganos procedentes del pollo. Es muy frecuente encontrarla en muchos platos.', 5, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Pollo.jpg', 2, '100 grs', '615 mg', '190 mg', '205 mg');

#PESCADO
INSERT INTO foods VALUES (null, 'Almeja', 'Molusco marino de valvas casi ovaladas, con estrías finas y de color blanco grisáceo; vive en los fondos arenosos de aguas poco profundas y su carne es comestible y muy apreciada.', 6, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Almeja.jpg', 2, '100 grs', '601 mg', '46 mg', '198 mg');
INSERT INTO foods VALUES (null, 'Atun', 'Pez marino de 2 a 3 m de longitud, color azul oscuro en el dorso y plateado en el vientre, que tiene de 8 a 10 pínulas o diminutas aletas junto a la cola, su carne es comestible.', 6, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Atun.jpg', 2, '100 grs', '39 mg', '252 mg', '254 mg');
INSERT INTO foods VALUES (null, 'Bacalao', 'Pez marino de hasta 170 cm de longitud, cuerpo alargado, color verde oliváceo, más claro en la parte ventral y en los flancos, con la cabeza grande, tres aletas dorsales y dos anales, su carne es comestible.', 6, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Bacalao.jpg', 2, '100 grs', '54 mg', '413 mg', '203 mg');
INSERT INTO foods VALUES (null, 'Langosta', 'Crustáceo marino decápodo de hasta 50 cm de longitud, color pardo oscuro, cuerpo alargado casi cilíndrico cubierto de tegumentos articulados duros y espinosos, cabeza grande, ojos prominentes, antenas muy largas, su carne es comestible y muy apreciada.', 6, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Langosta.jpg', 2, '100 grs', '423 mg', '200 mg', '161 mg');
INSERT INTO foods VALUES (null, 'Robalo', 'Pez marino comestible de color blanco y plateado, de 50 cm de longitud, que tiene dos aletas dorsales y una raya oscura entre el dorso y el vientre; suele remontar grandes ríos.', 6, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Robalo.jpg', 1, '100 grs', '52 mg', '302 mg', '170 mg');
INSERT INTO foods VALUES (null, 'Sardina', 'Pez marino de unos 25 cm de longitud, color azul en el dorso y plateado en los costados y en el vientre, cuerpo alargado y aleta caudal muy escotada, tiene alto valor nutritivo.', 6, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Sardina.jpg', 1, '100 grs', '307 mg', '397 mg', '490 mg');

#OTROS
INSERT INTO foods VALUES (null, 'Albahaca', 'Planta herbácea, muy olorosa, de tallos ramosos y velludos, hojas pequeñas muy verdes y flores blancas; puede alcanzar 30 cm de altura.', 7, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Albahaca.jpg', 1, '100 grs','4 mg', '295 mg', '56 mg');
INSERT INTO foods VALUES (null, 'Hierbabuena', 'Planta herbácea de tallos erguidos, poco ramosos, hojas vellosas, lanceoladas, de borde aserrado y color verde, flores rojizas, agrupadas al final del tallo y fruto seco, con cuatro semillas; es muy aromática.', 7, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Hierbabuena.jpg', 1, '100 grs', '30 mg', '458 mg', '60 mg');
INSERT INTO foods VALUES (null, 'Oregano', 'Planta aromática de tallos vellosos, hojas pequeñas y ovaladas, flores rosadas o malvas, agrupadas en espiga y fruto seco y globoso.', 7,  'http://ezpo.tech/kidney/Kidneys/Images/Foods/Oregano.jpg', 1, '100 grs', '25 mg', '1 mg', '148 mg');
INSERT INTO foods VALUES (null, 'Laurel', 'Árbol de tronco liso, corteza delgada, hojas perennes, lanceoladas, de color verde oscuro y de aroma agradable; puede alcanzar hasta 12 m de altura y tiene aspecto de mata.', 7, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Laurel.jpg', 1, '100 grs', '23 mg', '529 mg', '113 mg');
INSERT INTO foods VALUES (null, 'Romero', 'Arbusto aromático de ramas erectas, ascendentes y ocasionalmente extendidas, de corteza gris, hojas opuestas en cruz, lineales y con bordes enrollados, de color verde intenso y flores de color azul claro o violáceo.', 7, 'http://ezpo.tech/kidney/Kidneys/Images/Foods/Romero.jpg', 1, '100 grs', '50 mg', '955 mg', '70 mg');

