use kidneys;

INSERT INTO questions VAlUES (null,'¿La aplicación es gratis?', 'Si. La aplicación de Kidneys puede descargarse e instalarse sin coste alguno. Sin embargo, solo los suscriptores premium tendran acceso a la aplicación sin publicidad.');
INSERT INTO questions VALUES (null,'¿Tengo que registrarme?', 'Si, es completamente necesario que el usuario este registrado con nosotros, para que se tenga la información completa de su perfil.');
INSERT INTO questions VALUES (null,'¿En que dispositivos funciona?', 'Por el momento solo estamos disponibles en dispositivos Android.');
INSERT INTO questions VALUES (null,'¿Es imprescindible instalar las actualizaciones?', 'Las actualizaciones son necesarias para corregir fallos, para afinar el funcionamiento y para añadir mejoras y nuevos contenidos. Si no instalas las actualizaciones, es posible que no puedas ver algunos contenidos, y que persistan algunos fallos.');
INSERT INTO questions VALUES (null,'¿Cómo descargo las guías?', 'Las guias se descargan pulsando el boton que se encuentra abajo de la leyenda "Descargar" entrando en la seccion de tratamiendo.');
INSERT INTO questions VALUES (null,'¿Cómo cambio de color la interfaz de la aplicación?', 'En la parte superior derecha de la pantalla se encuentra una tuerca (pulsar) y unas vez ahí se pueden cambiar a color amarillo, azul o rosado.');
INSERT INTO questions VALUES (null,'¿Qué encontrare en la sección de Mapa?', 'Creamos la sección de mapa, para que el usuario tenga a la mano las clinicas, hospitales o distribuidores que se encuentren en la zona de Veracruz y asi facilitarles el proceso de encontrar direcciones de dichos lugares.');
INSERT INTO questions VALUES (null,'¿Qué puedo hacer si tengo alguna duda de como se usa la aplicación?', 'En caso de tener dudas, puedes visitar el modulo de ayuda, aquí encontraras información que puede ser de utilidad, si después de eso, aun se tienen dudas o sugerencias, puedes mandar un correo entrando en el módulo de contacto y pulsado en el boton que esta en la parte inferior central.');
